import Foundation

/// Generates Apple Configuration Profile (.mobileconfig) XML for rules that support MDM deployment.
///
/// The generated profiles can be imported into Jamf Pro, Microsoft Intune, Mosyle, Kandji,
/// or any other MDM solution that supports Apple Configuration Profiles.
public struct MobileConfigGenerator {

    // MARK: - Public

    /// Generate a single .mobileconfig XML string containing payloads for all MDM-deployable rules.
    /// - Parameters:
    ///   - rules: The rules to include (only those with mobileconfig == true will be included).
    ///   - profile: The compliance profile this configuration is targeting.
    ///   - orgName: Your organisation name (embedded in the profile description).
    ///   - profileIdentifier: Reverse-DNS identifier for the profile, e.g. "com.example.stig-baseline"
    public static func generate(
        rules: [Rule],
        profile: ComplianceProfile,
        orgName: String = "Your Organization",
        profileIdentifier: String = "com.stigit.baseline"
    ) -> String {
        let eligible = rules.filter { $0.profiles.contains(profile) && $0.mobileconfig }

        // Group rules by their payload domain so we can merge keys into a single payload per domain
        var domainPayloads: [String: [(key: String, value: Any)]] = [:]
        for rule in eligible {
            if let (domain, key, value) = payloadInfo(for: rule) {
                domainPayloads[domain, default: []].append((key: key, value: value))
            }
        }

        let payloadUUID  = UUID().uuidString.uppercased()
        let timestamp    = ISO8601DateFormatter().string(from: Date())

        var payloadArray = ""
        var payloadIdx = 0
        for (domain, kvPairs) in domainPayloads.sorted(by: { $0.key < $1.key }) {
            let payloadItemUUID = UUID().uuidString.uppercased()
            payloadIdx += 1

            var keysXML = ""
            for kv in kvPairs {
                keysXML += "\t\t\t<key>\(kv.key)</key>\n"
                keysXML += "\t\t\t\(xmlValue(kv.value))\n"
            }

            payloadArray += """
            \t\t<dict>
            \t\t\t<key>PayloadType</key>
            \t\t\t<string>com.apple.ManagedClient.preferences</string>
            \t\t\t<key>PayloadIdentifier</key>
            \t\t\t<string>\(profileIdentifier).item\(payloadIdx)</string>
            \t\t\t<key>PayloadUUID</key>
            \t\t\t<string>\(payloadItemUUID)</string>
            \t\t\t<key>PayloadVersion</key>
            \t\t\t<integer>1</integer>
            \t\t\t<key>PayloadDisplayName</key>
            \t\t\t<string>\(domain)</string>
            \t\t\t<key>PayloadDomain</key>
            \t\t\t<string>\(domain)</string>
            \t\t\t<key>PayloadEnabled</key>
            \t\t\t<true/>
            \t\t\t<!-- Managed preference keys -->
            \(keysXML)\t\t</dict>\n
            """
        }

        return """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        \t<key>PayloadDisplayName</key>
        \t<string>StigIt \(profile.rawValue) Security Baseline</string>
        \t<key>PayloadDescription</key>
        \t<string>Generated by StigIt for \(orgName) on \(timestamp). Applies \(profile.rawValue) controls to managed macOS endpoints.</string>
        \t<key>PayloadIdentifier</key>
        \t<string>\(profileIdentifier)</string>
        \t<key>PayloadOrganization</key>
        \t<string>\(orgName)</string>
        \t<key>PayloadRemovalDisallowed</key>
        \t<true/>
        \t<key>PayloadScope</key>
        \t<string>System</string>
        \t<key>PayloadType</key>
        \t<string>Configuration</string>
        \t<key>PayloadUUID</key>
        \t<string>\(payloadUUID)</string>
        \t<key>PayloadVersion</key>
        \t<integer>1</integer>
        \t<key>PayloadContent</key>
        \t<array>
        \(payloadArray)\t</array>
        </dict>
        </plist>
        """
    }

    /// Write a .mobileconfig file to disk.  Returns the URL of the written file.
    @discardableResult
    public static func write(
        rules: [Rule],
        profile: ComplianceProfile,
        orgName: String = "Your Organization",
        profileIdentifier: String = "com.stigit.baseline",
        to directory: URL = MobileConfigGenerator.defaultOutputDirectory()
    ) throws -> URL {
        let xml = generate(rules: rules, profile: profile, orgName: orgName, profileIdentifier: profileIdentifier)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let profileName = "\(profileIdentifier)_\(profile.id.lowercased().replacingOccurrences(of: " ", with: "_")).mobileconfig"
        let url = directory.appendingPathComponent(profileName)
        try xml.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    public static func defaultOutputDirectory() -> URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".stigit/profiles")
    }

    // MARK: - Private helpers

    /// Returns the (payloadDomain, key, value) tuple for a given rule's MDM payload.
    /// Only rules that are known to support mobileconfig delivery are mapped here.
    private static func payloadInfo(for rule: Rule) -> (domain: String, key: String, value: Any)? {
        switch rule.id {
        // Firewall
        case "system_settings_firewall_enable":
            return ("com.apple.security.firewall", "EnableFirewall", true)
        case "system_settings_firewall_stealth_mode_enable":
            return ("com.apple.security.firewall", "EnableStealthMode", true)

        // Gatekeeper
        case "os_gatekeeper_enable":
            return ("com.apple.systempolicy.control", "EnableAssessment", true)
        case "system_settings_gatekeeper_override_disallow":
            return ("com.apple.systempolicy.managed", "DisableOverride", true)

        // FileVault
        case "system_settings_filevault_enforce":
            return ("com.apple.MCX", "dontAllowFDEDisable", true)

        // Bonjour
        case "os_bonjour_disable":
            return ("com.apple.mDNSResponder", "NoMulticastAdvertisements", true)

        // Content caching
        case "system_settings_content_caching_disable":
            return ("com.apple.AssetCache", "Activated", false)

        // AirPlay receiver
        case "system_settings_airplay_receiver_disable":
            return ("com.apple.AirPlayReceiver", "AirPlayEnabled", false)

        // SmartCard
        case "auth_smartcard_enforce":
            return ("com.apple.security.smartcard", "enforceSmartCard", true)

        // Camera
        case "os_camera_disable":
            return ("com.apple.applicationaccess", "allowCamera", false)

        // Media
        case "os_blank_bluray_disable":
            return ("com.apple.systempreferences", "DisableBlankBluRaySaving", true)
        case "os_blank_cd_disable":
            return ("com.apple.systempreferences", "DisableBlankCDSaving", true)
        case "os_blank_dvd_disable":
            return ("com.apple.systempreferences", "DisableBlankDVDSaving", true)

        // Diagnostics
        case "system_settings_diagnostics_reports_disable":
            return ("com.apple.SubmitDiagInfo", "AutoSubmit", false)

        default:
            return nil
        }
    }

    private static func xmlValue(_ value: Any) -> String {
        switch value {
        case let b as Bool:   return b ? "<true/>" : "<false/>"
        case let i as Int:    return "<integer>\(i)</integer>"
        case let s as String: return "<string>\(xmlEscape(s))</string>"
        default:              return "<string>\(xmlEscape(String(describing: value)))</string>"
        }
    }

    private static func xmlEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "&",  with: "&amp;")
         .replacingOccurrences(of: "<",  with: "&lt;")
         .replacingOccurrences(of: ">",  with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
